apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  #namespace: portainer
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4050Mi


#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mypvcportainer
#  namespace: portainer
#spec:
#  storageClassName: standard
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 4050Mi
