apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-org1
spec:
  selector:
    matchLabels:
      app: ca-org1
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-org1
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: svc
                    operator: In
                    values:
                      - peer
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: ca-org1
          image: hyperledger/fabric-ca:1.5.5
          imagePullPolicy: "IfNotPresent"
          command:
            [
              "fabric-ca-server" ,
              "start", "-b" ,"admin:adminpw","--port","8054", "-d"
            ]
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "150m"
          env:
           - name: FABRIC_CA_SERVER_CA_NAME
             value: ca-org1
           - name: FABRIC_CA_SERVER_TLS_ENABLED
             value: "true"
           - name: FABRIC_CA_SERVER_CSR_CN
             value: "ca-org1"
           - name: FABRIC_CA_SERVER_CSR_HOSTS
             value: "ca-org1"
           - name: FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY
             value: "true"
          volumeMounts:
            - name: data
              mountPath: /etc/hyperledger/fabric-ca-server
              subPath: organizations/fabric-ca/org1