apiVersion: v1
kind: PersistentVolume
metadata:
  name: blockchain-shared-common-msp-certs-ubf31
spec:
  capacity:
    storage: 5Gi  # Not bound to this storage just for pvc to bound to this pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/Common-Shared-MSP-Certs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ubf31  # local volume for ubf31
