apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-pvc-ubf31
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  volumeName: blockchain-pv-ubf31  # Ensures binding to that exact PV mathcing pv name using keywork volumeName
