kind: Service
apiVersion: v1
metadata:
  name: peer2-org1
  labels:
    app: peer2-org1
spec:
  selector:
    name: peer2-org1
  type: ClusterIP
  ports:
    - name: grpc
      port: 7051
      protocol: TCP
    - name: event
      port: 7060
      protocol: TCP
    - name: couchdb
      port: 5984
      protocol: TCP

---
#---------------- peer2 Org1 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer2-org1
    metrics-service: "true"
  name: peer2-org1-metrics
spec:
  type: ClusterIP
  ports:
  - name: "peer-metrics"
    port: 9445
    targetPort: 9445
  selector:
    name: peer2-org1
